challenges/urls.py
from django.urls import path

from . import views


app_name = 'challenges'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:month>/', views.monthly_challenge_by_number),
    path('<str:month>/', views.monthly_challenge, name='str-month-challenge'),
]

monthly_challenges/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('challenges/', include('challenges.urls'))
]

challenges/models.py
from django.db import models

# Create your models here.

challenges/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest, HttpResponseNotFound
from django.http import HttpResponseBadRequest, HttpResponseRedirect, Http404
from django.urls import reverse

monthly_challenges = {
    'january': 'Eat no meat for an entire month!',
    'february': 'Read a new book each week!',
    'march': 'Learn a new language for 30 minutes a day!',
    'april': 'Run 5 kilometers three times a week!',
    'may': 'Practice yoga for 30 minutes every day!',
    'june': 'Cook a new recipe every day!',
    'july': 'Write a journal entry every day!',
    'august': 'Explore a new hiking trail each weekend!',
    'september': 'Complete a daily drawing challenge!',
    'october': 'Try a new workout routine every week!',
    'november': 'Learn to play a new musical instrument!',
    'december': None
}


def index(request):
    months = list(monthly_challenges.keys())
    return render(request, 'challenges/index.html', {'months': months})


def monthly_challenge(request: HttpRequest, month: str) -> HttpResponse:
    challenges = monthly_challenges
    if month not in challenges:
        raise Http404()

    context = {'month': month,
               'challenge': challenges[month]}
    return render(request, 'challenges/challenge.html', context)


def monthly_challenge_by_number(request: HttpRequest, month: int) -> HttpResponse:
    if month not in range(1, 13):
        return HttpResponseBadRequest(f"<b>400</b> - No month with number: {month}")
    months = list(monthly_challenges.keys())
    redirect_month = months[month - 1]
    return HttpResponseRedirect(reverse('challenges:str-month-challenge',
                                        kwargs={'month': redirect_month}))

challenges/templates/challenges/challenge.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
{{ month|title }} Challenge
{% endblock %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'challenges/challenge.css' %}?timestamp={% now 'U' %}">
<link rel="stylesheet" href="{% static 'challenges/includes/header.css' %}?timestamp={% now 'U' %}">
{% endblock %}

{% block navbar %}
{% include 'challenges/includes/navbar.html' %}
{% endblock %}

{% block content %}
<main>
    <section>
        <h1>{% now "Y" %} {{ month|title }}'s challenge</h1>
        {% if not challenge %}
        <p class="fallback">No challenge set for this month</p>
        {% else %}
        <p>{{ challenge }}</p>
        {% endif %}
    </section>
</main>
{% endblock %}

challenges/templates/challenges/includes/navbar.html
<nav>
    <a href="{% url 'challenges:index'%}">All Monthly Challenges</a>
</nav>

challenges/templates/challenges/index.html
{% extends 'base.html' %}
{% load static %}


{% block css_files %}
<link rel="stylesheet" href="{% static 'challenges/challenges.css' %}?timestamp={% now 'U' %}">
<link rel="stylesheet" href="{% static 'challenges/includes/header.css' %}?timestamp={% now 'U' %}">
{% endblock %}

{% block page_title %}
Monthly Challenges
{% endblock %}

{% block navbar %}
{% include 'challenges/includes/navbar.html' %}
{% endblock %}


{% block content %}

<main>
    <section>
        <ul>
            {% for month in months %}
            <li><a href="{% url 'challenges:str-month-challenge' month=month%}">{{ month|title }}</a></li>
            {% endfor %}
        </ul>
    </section>
</main>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %}My Challenges{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}?timestamp={% now 'U' %}">
    {% block css_files %}{% endblock %}
</head>

<body>
    <header>
        {% block navbar %}
        {% endblock%}
    </header>
    {% block content %}
    {% endblock %}
    <footer></footer>
</body>

</html>